// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }



import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GateKey — API Key Management for Developers',
  description: 'Generate, manage, and monitor API keys with built-in rate limiting and circuit breaker protection. Start free.',
  openGraph: {
    title: 'GateKey — API Key Management for Developers',
    description: 'Generate, manage, and monitor API keys with built-in rate limiting and circuit breaker protection.',
    url: 'https://your-dashboard.vercel.app',
    siteName: 'GateKey',
    type: 'website'
  },
  twitter: {
    card: 'summary_large_image',
    title: 'GateKey — API Key Management for Developers',
    description: 'Generate, manage, and monitor API keys with built-in rate limiting and circuit breaker protection.'
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}